#!/usr/bin/env php
<?php

/**
 * This file is part of the sj-i/wpfs package.
 *
 * (c) sji <sji@sj-i.dev>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

use DI\ContainerBuilder;
use Symfony\Component\Console\Application;
use Wpfs\WpfsCommand;

require __DIR__ . '/vendor/autoload.php';

$application = new Application();
$container = (new ContainerBuilder())->build();
$command = $container->make(WpfsCommand::class);
$application->add($command);
$application->run();
